package com.samuel.vikitechnicaltest.business.domain.models

data class ConversionRates constructor(
    val AED: Float,
    val AFN: Float,
    val ALL: Float,
    val AMD: Float,
    val ANG: Float,
    val AOA: Float,
    val ARS: Float,
    val AUD: Float,
    val AWG: Float,
    val AZN: Float,
    val BAM: Float,
    val BBD: Float,
    val BDT: Float,
    val BGN: Float,
    val BHD: Float,
    val BIF: Float,
    val BMD: Float,
    val BND: Float,
    val BOB: Float,
    val BRL: Float,
    val BSD: Float,
    val BTN: Float,
    val BWP: Float,
    val BYN: Float,
    val BZD: Float,
    val CAD: Float,
    val CDF: Float,
    val CHF: Float,
    val CLP: Float,
    val CNY: Float,
    val COP: Float,
    val CRC: Float,
    val CUP: Float,
    val CVE: Float,
    val CZK: Float,
    val DJF: Float,
    val DKK: Float,
    val DOP: Float,
    val DZD: Float,
    val EGP: Float,
    val ERN: Float,
    val ETB: Float,
    val EUR: Float,
    val FJD: Float,
    val FKP: Float,
    val FOK: Float,
    val GBP: Float,
    val GEL: Float,
    val GGP: Float,
    val GHS: Float,
    val GIP: Float,
    val GMD: Float,
    val GNF: Float,
    val GTQ: Float,
    val GYD: Float,
    val HKD: Float,
    val HNL: Float,
    val HRK: Float,
    val HTG: Float,
    val HUF: Float,
    val IDR: Float,
    val ILS: Float,
    val IMP: Float,
    val INR: Float,
    val IQD: Float,
    val IRR: Float,
    val ISK: Float,
    val JEP: Float,
    val JMD: Float,
    val JOD: Float,
    val JPY: Float,
    val KES: Float,
    val KGS: Float,
    val KHR: Float,
    val KID: Float,
    val KMF: Float,
    val KRW: Float,
    val KWD: Float,
    val KYD: Float,
    val KZT: Float,
    val LAK: Float,
    val LBP: Float,
    val LKR: Float,
    val LRD: Float,
    val LSL: Float,
    val LYD: Float,
    val MAD: Float,
    val MDL: Float,
    val MGA: Float,
    val MKD: Float,
    val MMK: Float,
    val MNT: Float,
    val MOP: Float,
    val MRU: Float,
    val MUR: Float,
    val MVR: Float,
    val MWK: Float,
    val MXN: Float,
    val MYR: Float,
    val MZN: Float,
    val NAD: Float,
    val NGN: Float,
    val NIO: Float,
    val NOK: Float,
    val NPR: Float,
    val NZD: Float,
    val OMR: Float,
    val PAB: Float,
    val PEN: Float,
    val PGK: Float,
    val PHP: Float,
    val PKR: Float,
    val PLN: Float,
    val PYG: Float,
    val QAR: Float,
    val RON: Float,
    val RSD: Float,
    val RUB: Float,
    val RWF: Float,
    val SAR: Float,
    val SBD: Float,
    val SCR: Float,
    val SDG: Float,
    val SEK: Float,
    val SGD: Int,
    val SHP: Float,
    val SLE: Float,
    val SLL: Float,
    val SOS: Float,
    val SRD: Float,
    val SSP: Float,
    val STN: Float,
    val SYP: Float,
    val SZL: Float,
    val THB: Float,
    val TJS: Float,
    val TMT: Float,
    val TND: Float,
    val TOP: Float,
    val TRY: Float,
    val TTD: Float,
    val TVD: Float,
    val TWD: Float,
    val TZS: Float,
    val UAH: Float,
    val UGX: Float,
    val USD: Float,
    val UYU: Float,
    val UZS: Float,
    val VES: Float,
    val VND: Float,
    val VUV: Float,
    val WST: Float,
    val XAF: Float,
    val XCD: Float,
    val XDR: Float,
    val XOF: Float,
    val XPF: Float,
    val YER: Float,
    val ZAR: Float,
    val ZMW: Float,
    val ZWL: Float
) {

    companion object {
        fun getCountryCodes(): List<String> {
            return listOf(
                "AED",
                "AFN",
                "ALL",
                "AMD",
                "ANG",
                "AOA",
                "ARS",
                "AUD",
                "AWG",
                "AZN",
                "BAM",
                "BBD",
                "BDT",
                "BGN",
                "BHD",
                "BIF",
                "BMD",
                "BND",
                "BOB",
                "BRL",
                "BSD",
                "BTN",
                "BWP",
                "BYN",
                "BZD",
                "CAD",
                "CDF",
                "CHF",
                "CLP",
                "CNY",
                "COP",
                "CRC",
                "CUP",
                "CVE",
                "CZK",
                "DJF",
                "DKK",
                "DOP",
                "DZD",
                "EGP",
                "ERN",
                "ETB",
                "EUR",
                "FJD",
                "FKP",
                "FOK",
                "GBP",
                "GEL",
                "GGP",
                "GHS",
                "GIP",
                "GMD",
                "GNF",
                "GTQ",
                "GYD",
                "HKD",
                "HNL",
                "HRK",
                "HTG",
                "HUF",
                "IDR",
                "ILS",
                "IMP",
                "INR",
                "IQD",
                "IRR",
                "ISK",
                "JEP",
                "JMD",
                "JOD",
                "JPY",
                "KES",
                "KGS",
                "KHR",
                "KID",
                "KMF",
                "KRW",
                "KWD",
                "KYD",
                "KZT",
                "LAK",
                "LBP",
                "LKR",
                "LRD",
                "LSL",
                "LYD",
                "MAD",
                "MDL",
                "MGA",
                "MKD",
                "MMK",
                "MNT",
                "MOP",
                "MRU",
                "MUR",
                "MVR",
                "MWK",
                "MXN",
                "MYR",
                "MZN",
                "NAD",
                "NGN",
                "NIO",
                "NOK",
                "NPR",
                "NZD",
                "OMR",
                "PAB",
                "PEN",
                "PGK",
                "PHP",
                "PKR",
                "PLN",
                "PYG",
                "QAR",
                "RON",
                "RSD",
                "RUB",
                "RWF",
                "SAR",
                "SBD",
                "SCR",
                "SDG",
                "SEK",
                "SGD",
                "SHP",
                "SLE",
                "SLL",
                "SOS",
                "SRD",
                "SSP",
                "STN",
                "SYP",
                "SZL",
                "THB",
                "TJS",
                "TMT",
                "TND",
                "TOP",
                "TRY",
                "TTD",
                "TVD",
                "TWD",
                "TZS",
                "UAH",
                "UGX",
                "USD",
                "UYU",
                "UZS",
                "VES",
                "VND",
                "VUV",
                "WST",
                "XAF",
                "XCD",
                "XDR",
                "XOF",
                "XPF",
                "YER",
                "ZAR",
                "ZMW",
                "ZWL"
            )
        }
    }


    fun getRatesList(): List<Float> {
        return listOf(
            AED,
            AFN,
            ALL,
            AMD,
            ANG,
            AOA,
            ARS,
            AUD,
            AWG,
            AZN,
            BAM,
            BBD,
            BDT,
            BGN,
            BHD,
            BIF,
            BMD,
            BND,
            BOB,
            BRL,
            BSD,
            BTN,
            BWP,
            BYN,
            BZD,
            CAD,
            CDF,
            CHF,
            CLP,
            CNY,
            COP,
            CRC,
            CUP,
            CVE,
            CZK,
            DJF,
            DKK,
            DOP,
            DZD,
            EGP,
            ERN,
            ETB,
            EUR,
            FJD,
            FKP,
            FOK,
            GBP,
            GEL,
            GGP,
            GHS,
            GIP,
            GMD,
            GNF,
            GTQ,
            GYD,
            HKD,
            HNL,
            HRK,
            HTG,
            HUF,
            IDR,
            ILS,
            IMP,
            INR,
            IQD,
            IRR,
            ISK,
            JEP,
            JMD,
            JOD,
            JPY,
            KES,
            KGS,
            KHR,
            KID,
            KMF,
            KRW,
            KWD,
            KYD,
            KZT,
            LAK,
            LBP,
            LKR,
            LRD,
            LSL,
            LYD,
            MAD,
            MDL,
            MGA,
            MKD,
            MMK,
            MNT,
            MOP,
            MRU,
            MUR,
            MVR,
            MWK,
            MXN,
            MYR,
            MZN,
            NAD,
            NGN,
            NIO,
            NOK,
            NPR,
            NZD,
            OMR,
            PAB,
            PEN,
            PGK,
            PHP,
            PKR,
            PLN,
            PYG,
            QAR,
            RON,
            RSD,
            RUB,
            RWF,
            SAR,
            SBD,
            SCR,
            SDG,
            SEK,
            SGD.toFloat(),
            SHP,
            SLE,
            SLL,
            SOS,
            SRD,
            SSP,
            STN,
            SYP,
            SZL,
            THB,
            TJS,
            TMT,
            TND,
            TOP,
            TRY,
            TTD,
            TVD,
            TWD,
            TZS,
            UAH,
            UGX,
            USD,
            UYU,
            UZS,
            VES,
            VND,
            VUV,
            WST,
            XAF,
            XCD,
            XDR,
            XOF,
            XPF,
            YER,
            ZAR,
            ZMW,
            ZWL
        )
    }
    fun getCountryCodeRateList(): List<Pair<String, Float>> {
        return listOf(
            "AED" to AED,
            "AFN" to AFN,
            "ALL" to ALL,
            "AMD" to AMD,
            "ANG" to ANG,
            "AOA" to AOA,
            "ARS" to ARS,
            "AUD" to AUD,
            "AWG" to AWG,
            "AZN" to AZN,
            "BAM" to BAM,
            "BBD" to BBD,
            "BDT" to BDT,
            "BGN" to BGN,
            "BHD" to BHD,
            "BIF" to BIF,
            "BMD" to BMD,
            "BND" to BND,
            "BOB" to BOB,
            "BRL" to BRL,
            "BSD" to BSD,
            "BTN" to BTN,
            "BWP" to BWP,
            "BYN" to BYN,
            "BZD" to BZD,
            "CAD" to CAD,
            "CDF" to CDF,
            "CHF" to CHF,
            "CLP" to CLP,
            "CNY" to CNY,
            "COP" to COP,
            "CRC" to CRC,
            "CUP" to CUP,
            "CVE" to CVE,
            "CZK" to CZK,
            "DJF" to DJF,
            "DKK" to DKK,
            "DOP" to DOP,
            "DZD" to DZD,
            "EGP" to EGP,
            "ERN" to ERN,
            "ETB" to ETB,
            "EUR" to EUR,
            "FJD" to FJD,
            "FKP" to FKP,
            "FOK" to FOK,
            "GBP" to GBP,
            "GEL" to GEL,
            "GGP" to GGP,
            "GHS" to GHS,
            "GIP" to GIP,
            "GMD" to GMD,
            "GNF" to GNF,
            "GTQ" to GTQ,
            "GYD" to GYD,
            "HKD" to HKD,
            "HNL" to HNL,
            "HRK" to HRK,
            "HTG" to HTG,
            "HUF" to HUF,
            "IDR" to IDR,
            "ILS" to ILS,
            "IMP" to IMP,
            "INR" to INR,
            "IQD" to IQD,
            "IRR" to IRR,
            "ISK" to ISK,
            "JEP" to JEP,
            "JMD" to JMD,
            "JOD" to JOD,
            "JPY" to JPY,
            "KES" to KES,
            "KGS" to KGS,
            "KHR" to KHR,
            "KID" to KID,
            "KMF" to KMF,
            "KRW" to KRW,
            "KWD" to KWD,
            "KYD" to KYD,
            "KZT" to KZT,
            "LAK" to LAK,
            "LBP" to LBP,
            "LKR" to LKR,
            "LRD" to LRD,
            "LSL" to LSL,
            "LYD" to LYD,
            "MAD" to MAD,
            "MDL" to MDL,
            "MGA" to MGA,
            "MKD" to MKD,
            "MMK" to MMK,
            "MNT" to MNT,
            "MOP" to MOP,
            "MRU" to MRU,
            "MUR" to MUR,
            "MVR" to MVR,
            "MWK" to MWK,
            "MXN" to MXN,
            "MYR" to MYR,
            "MZN" to MZN,
            "NAD" to NAD,
            "NGN" to NGN,
            "NIO" to NIO,
            "NOK" to NOK,
            "NPR" to NPR,
            "NZD" to NZD,
            "OMR" to OMR,
            "PAB" to PAB,
            "PEN" to PEN,
            "PGK" to PGK,
            "PHP" to PHP,
            "PKR" to PKR,
            "PLN" to PLN,
            "PYG" to PYG,
            "QAR" to QAR,
            "RON" to RON,
            "RSD" to RSD,
            "RUB" to RUB,
            "RWF" to RWF,
            "SAR" to SAR,
            "SBD" to SBD,
            "SCR" to SCR,
            "SDG" to SDG,
            "SEK" to SEK,
            "SGD" to SGD.toFloat(),
            "SHP" to SHP,
            "SLE" to SLE,
            "SLL" to SLL,
            "SOS" to SOS,
            "SRD" to SRD,
            "SSP" to SSP,
            "STN" to STN,
            "SYP" to SYP,
            "SZL" to SZL,
            "THB" to THB,
            "TJS" to TJS,
            "TMT" to TMT,
            "TND" to TND,
            "TOP" to TOP,
            "TRY" to TRY,
            "TTD" to TTD,
            "TVD" to TVD,
            "TWD" to TWD,
            "TZS" to TZS,
            "UAH" to UAH,
            "UGX" to UGX,
            "USD" to USD,
            "UYU" to UYU,
            "UZS" to UZS,
            "VES" to VES,
            "VND" to VND,
            "VUV" to VUV,
            "WST" to WST,
            "XAF" to XAF,
            "XCD" to XCD,
            "XDR" to XDR,
            "XOF" to XOF,
            "XPF" to XPF,
            "YER" to YER,
            "ZAR" to ZAR,
            "ZMW" to ZMW,
            "ZWL" to ZWL
        )
    }
}